# version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: turbogastos-redis
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  ingestor:
    build:
      context: ./ingestor
      dockerfile: Dockerfile.node
    container_name: turbogastos-node-ingestor
    restart: unless-stopped
    shm_size: 512m
    volumes:
      - ./ingestor/sessions:/app/sessions
    ports:
      - "3000:3000"
    env_file:
      - ./ingestor/.env
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.python
    container_name: turbogastos-python-worker
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - "8000:8000"
    env_file:
      - ./worker/.env
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: turbogastos-frontend
    ports:
      - "5173:80"
    depends_on:
      - worker

  mcp-sqlite:
    build:
      context: ./mcp_service
    container_name: turbogastos-mcp-sqlite
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"
    environment:
      - DB_PATH=/data/gastos.db
    depends_on:
      worker:
        condition: service_healthy

  gmail-reader:
    build:
      context: ./gmail_reader
    container_name: turbogastos-gmail-reader
    restart: unless-stopped
    volumes:
      - ./gmail_reader:/app
    ports:
      - "8081:8081"
    env_file:
      - ./gmail_reader/.env
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis-data:
    driver: local
  sessions:
    driver: local
  data: # For SQLite DB
    driver: local