[project]
name = "mcp-sqlite-service"
version = "0.1.0"
description = "MCP-SQLite server"
requires-python = ">=3.12"

dependencies = [
    "mcp-sqlite"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"